/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedOrgsRouteImport } from './routes/_authenticated/orgs'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedOrgsIndexRouteImport } from './routes/_authenticated/orgs.index'
import { Route as AuthenticatedOrgsOrgIdRouteImport } from './routes/_authenticated/orgs.$orgId'
import { Route as AuthenticatedOrgsOrgIdIndexRouteImport } from './routes/_authenticated/orgs.$orgId.index'
import { Route as AuthenticatedOrgsOrgIdAgentsRouteImport } from './routes/_authenticated/orgs.$orgId.agents'
import { Route as AuthenticatedOrgsOrgIdMembersRouteImport } from './routes/_authenticated/orgs.$orgId.members'
import { Route as AuthenticatedOrgsOrgIdSettingsRouteImport } from './routes/_authenticated/orgs.$orgId.settings'
import { Route as AuthenticatedOrgsOrgIdAgentsIndexRouteImport } from './routes/_authenticated/orgs.$orgId.agents.index'
import { Route as AuthenticatedOrgsOrgIdAgentsAgentIdRouteImport } from './routes/_authenticated/orgs.$orgId.agents.$agentId'
import { Route as ApiPublicExotelAudioAudioIdRouteImport } from './routes/api/public/exotel/audio.$audioId'
import { Route as ApiPublicExotelVoiceAudioIdRouteImport } from './routes/api/public/exotel/voice.$audioId'
import { Route as AuthenticatedOrgsOrgIdAgentsAgentIdIndexRouteImport } from './routes/_authenticated/orgs.$orgId.agents.$agentId.index'
import { Route as AuthenticatedOrgsOrgIdAgentsAgentIdSettingsRouteImport } from './routes/_authenticated/orgs.$orgId.agents.$agentId.settings'
import { Route as AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRouteImport } from './routes/_authenticated/orgs.$orgId.agents.$agentId.flows.$flowId'
import { Route as AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRouteImport } from './routes/_authenticated/orgs.$orgId.agents.$agentId.flows.$flowId.index'
import { Route as AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRouteImport } from './routes/_authenticated/orgs.$orgId.agents.$agentId.flows.$flowId.versions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgsRoute = AuthenticatedOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgsIndexRoute = AuthenticatedOrgsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOrgsRoute,
} as any)
const AuthenticatedOrgsOrgIdRoute = AuthenticatedOrgsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AuthenticatedOrgsRoute,
} as any)
const AuthenticatedOrgsOrgIdIndexRoute =
  AuthenticatedOrgsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdAgentsRoute =
  AuthenticatedOrgsOrgIdAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdMembersRoute =
  AuthenticatedOrgsOrgIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdSettingsRoute =
  AuthenticatedOrgsOrgIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrgsOrgIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdAgentsIndexRoute =
  AuthenticatedOrgsOrgIdAgentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgsOrgIdAgentsRoute,
  } as any)
const AuthenticatedOrgsOrgIdAgentsAgentIdRoute =
  AuthenticatedOrgsOrgIdAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => AuthenticatedOrgsOrgIdAgentsRoute,
  } as any)
const ApiPublicExotelAudioAudioIdRoute =
  ApiPublicExotelAudioAudioIdRouteImport.update({
    id: '/api/public/exotel/audio/$audioId',
    path: '/api/public/exotel/audio/$audioId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExotelVoiceAudioIdRoute =
  ApiPublicExotelVoiceAudioIdRouteImport.update({
    id: '/api/public/exotel/voice/$audioId',
    path: '/api/public/exotel/voice/$audioId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute =
  AuthenticatedOrgsOrgIdAgentsAgentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgsOrgIdAgentsAgentIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdAgentsAgentIdSettingsRoute =
  AuthenticatedOrgsOrgIdAgentsAgentIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrgsOrgIdAgentsAgentIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRoute =
  AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRouteImport.update({
    id: '/flows/$flowId',
    path: '/flows/$flowId',
    getParentRoute: () => AuthenticatedOrgsOrgIdAgentsAgentIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute =
  AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRoute,
  } as any)
const AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute =
  AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/orgs': typeof AuthenticatedOrgsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/orgs/$orgId': typeof AuthenticatedOrgsOrgIdRouteWithChildren
  '/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/orgs/$orgId/agents': typeof AuthenticatedOrgsOrgIdAgentsRouteWithChildren
  '/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/orgs/$orgId/settings': typeof AuthenticatedOrgsOrgIdSettingsRoute
  '/orgs/$orgId/': typeof AuthenticatedOrgsOrgIdIndexRoute
  '/orgs/$orgId/agents/$agentId': typeof AuthenticatedOrgsOrgIdAgentsAgentIdRouteWithChildren
  '/api/public/exotel/audio/$audioId': typeof ApiPublicExotelAudioAudioIdRoute
  '/api/public/exotel/voice/$audioId': typeof ApiPublicExotelVoiceAudioIdRoute
  '/orgs/$orgId/agents/': typeof AuthenticatedOrgsOrgIdAgentsIndexRoute
  '/orgs/$orgId/agents/$agentId/settings': typeof AuthenticatedOrgsOrgIdAgentsAgentIdSettingsRoute
  '/orgs/$orgId/agents/$agentId/': typeof AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute
  '/orgs/$orgId/agents/$agentId/flows/$flowId': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRouteWithChildren
  '/orgs/$orgId/agents/$agentId/flows/$flowId/versions': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute
  '/orgs/$orgId/agents/$agentId/flows/$flowId/': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/orgs': typeof AuthenticatedOrgsIndexRoute
  '/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/orgs/$orgId/settings': typeof AuthenticatedOrgsOrgIdSettingsRoute
  '/orgs/$orgId': typeof AuthenticatedOrgsOrgIdIndexRoute
  '/api/public/exotel/audio/$audioId': typeof ApiPublicExotelAudioAudioIdRoute
  '/api/public/exotel/voice/$audioId': typeof ApiPublicExotelVoiceAudioIdRoute
  '/orgs/$orgId/agents': typeof AuthenticatedOrgsOrgIdAgentsIndexRoute
  '/orgs/$orgId/agents/$agentId/settings': typeof AuthenticatedOrgsOrgIdAgentsAgentIdSettingsRoute
  '/orgs/$orgId/agents/$agentId': typeof AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute
  '/orgs/$orgId/agents/$agentId/flows/$flowId/versions': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute
  '/orgs/$orgId/agents/$agentId/flows/$flowId': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/orgs': typeof AuthenticatedOrgsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/orgs/$orgId': typeof AuthenticatedOrgsOrgIdRouteWithChildren
  '/_authenticated/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/_authenticated/orgs/$orgId/agents': typeof AuthenticatedOrgsOrgIdAgentsRouteWithChildren
  '/_authenticated/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/_authenticated/orgs/$orgId/settings': typeof AuthenticatedOrgsOrgIdSettingsRoute
  '/_authenticated/orgs/$orgId/': typeof AuthenticatedOrgsOrgIdIndexRoute
  '/_authenticated/orgs/$orgId/agents/$agentId': typeof AuthenticatedOrgsOrgIdAgentsAgentIdRouteWithChildren
  '/api/public/exotel/audio/$audioId': typeof ApiPublicExotelAudioAudioIdRoute
  '/api/public/exotel/voice/$audioId': typeof ApiPublicExotelVoiceAudioIdRoute
  '/_authenticated/orgs/$orgId/agents/': typeof AuthenticatedOrgsOrgIdAgentsIndexRoute
  '/_authenticated/orgs/$orgId/agents/$agentId/settings': typeof AuthenticatedOrgsOrgIdAgentsAgentIdSettingsRoute
  '/_authenticated/orgs/$orgId/agents/$agentId/': typeof AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute
  '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRouteWithChildren
  '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/versions': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute
  '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/orgs'
    | '/profile'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/orgs/$orgId'
    | '/orgs/'
    | '/orgs/$orgId/agents'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/'
    | '/orgs/$orgId/agents/$agentId'
    | '/api/public/exotel/audio/$audioId'
    | '/api/public/exotel/voice/$audioId'
    | '/orgs/$orgId/agents/'
    | '/orgs/$orgId/agents/$agentId/settings'
    | '/orgs/$orgId/agents/$agentId/'
    | '/orgs/$orgId/agents/$agentId/flows/$flowId'
    | '/orgs/$orgId/agents/$agentId/flows/$flowId/versions'
    | '/orgs/$orgId/agents/$agentId/flows/$flowId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/orgs'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId'
    | '/api/public/exotel/audio/$audioId'
    | '/api/public/exotel/voice/$audioId'
    | '/orgs/$orgId/agents'
    | '/orgs/$orgId/agents/$agentId/settings'
    | '/orgs/$orgId/agents/$agentId'
    | '/orgs/$orgId/agents/$agentId/flows/$flowId/versions'
    | '/orgs/$orgId/agents/$agentId/flows/$flowId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/orgs'
    | '/_authenticated/profile'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/_authenticated/orgs/$orgId'
    | '/_authenticated/orgs/'
    | '/_authenticated/orgs/$orgId/agents'
    | '/_authenticated/orgs/$orgId/members'
    | '/_authenticated/orgs/$orgId/settings'
    | '/_authenticated/orgs/$orgId/'
    | '/_authenticated/orgs/$orgId/agents/$agentId'
    | '/api/public/exotel/audio/$audioId'
    | '/api/public/exotel/voice/$audioId'
    | '/_authenticated/orgs/$orgId/agents/'
    | '/_authenticated/orgs/$orgId/agents/$agentId/settings'
    | '/_authenticated/orgs/$orgId/agents/$agentId/'
    | '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId'
    | '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/versions'
    | '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicExotelAudioAudioIdRoute: typeof ApiPublicExotelAudioAudioIdRoute
  ApiPublicExotelVoiceAudioIdRoute: typeof ApiPublicExotelVoiceAudioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orgs': {
      id: '/_authenticated/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AuthenticatedOrgsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orgs/': {
      id: '/_authenticated/orgs/'
      path: '/'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AuthenticatedOrgsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsRoute
    }
    '/_authenticated/orgs/$orgId': {
      id: '/_authenticated/orgs/$orgId'
      path: '/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdRouteImport
      parentRoute: typeof AuthenticatedOrgsRoute
    }
    '/_authenticated/orgs/$orgId/': {
      id: '/_authenticated/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/agents': {
      id: '/_authenticated/orgs/$orgId/agents'
      path: '/agents'
      fullPath: '/orgs/$orgId/agents'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdAgentsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/members': {
      id: '/_authenticated/orgs/$orgId/members'
      path: '/members'
      fullPath: '/orgs/$orgId/members'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdMembersRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/settings': {
      id: '/_authenticated/orgs/$orgId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/settings'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdSettingsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdRoute
    }
    '/_authenticated/orgs/$orgId/agents/': {
      id: '/_authenticated/orgs/$orgId/agents/'
      path: '/'
      fullPath: '/orgs/$orgId/agents/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdAgentsRoute
    }
    '/_authenticated/orgs/$orgId/agents/$agentId': {
      id: '/_authenticated/orgs/$orgId/agents/$agentId'
      path: '/$agentId'
      fullPath: '/orgs/$orgId/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdAgentsRoute
    }
    '/api/public/exotel/audio/$audioId': {
      id: '/api/public/exotel/audio/$audioId'
      path: '/api/public/exotel/audio/$audioId'
      fullPath: '/api/public/exotel/audio/$audioId'
      preLoaderRoute: typeof ApiPublicExotelAudioAudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/exotel/voice/$audioId': {
      id: '/api/public/exotel/voice/$audioId'
      path: '/api/public/exotel/voice/$audioId'
      fullPath: '/api/public/exotel/voice/$audioId'
      preLoaderRoute: typeof ApiPublicExotelVoiceAudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orgs/$orgId/agents/$agentId/': {
      id: '/_authenticated/orgs/$orgId/agents/$agentId/'
      path: '/'
      fullPath: '/orgs/$orgId/agents/$agentId/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdRoute
    }
    '/_authenticated/orgs/$orgId/agents/$agentId/settings': {
      id: '/_authenticated/orgs/$orgId/agents/$agentId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/agents/$agentId/settings'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdSettingsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdRoute
    }
    '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId': {
      id: '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/orgs/$orgId/agents/$agentId/flows/$flowId'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdRoute
    }
    '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/': {
      id: '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/'
      path: '/'
      fullPath: '/orgs/$orgId/agents/$agentId/flows/$flowId/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRoute
    }
    '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/versions': {
      id: '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/versions'
      path: '/versions'
      fullPath: '/orgs/$orgId/agents/$agentId/flows/$flowId/versions'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRoute
    }
  }
}

interface AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRouteChildren {
  AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute
  AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute
}

const AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRouteChildren: AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRouteChildren =
  {
    AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute:
      AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute,
    AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute:
      AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute,
  }

const AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRouteWithChildren =
  AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRoute._addFileChildren(
    AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRouteChildren,
  )

interface AuthenticatedOrgsOrgIdAgentsAgentIdRouteChildren {
  AuthenticatedOrgsOrgIdAgentsAgentIdSettingsRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdSettingsRoute
  AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute
  AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRouteWithChildren
}

const AuthenticatedOrgsOrgIdAgentsAgentIdRouteChildren: AuthenticatedOrgsOrgIdAgentsAgentIdRouteChildren =
  {
    AuthenticatedOrgsOrgIdAgentsAgentIdSettingsRoute:
      AuthenticatedOrgsOrgIdAgentsAgentIdSettingsRoute,
    AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute:
      AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute,
    AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRoute:
      AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdRouteWithChildren,
  }

const AuthenticatedOrgsOrgIdAgentsAgentIdRouteWithChildren =
  AuthenticatedOrgsOrgIdAgentsAgentIdRoute._addFileChildren(
    AuthenticatedOrgsOrgIdAgentsAgentIdRouteChildren,
  )

interface AuthenticatedOrgsOrgIdAgentsRouteChildren {
  AuthenticatedOrgsOrgIdAgentsAgentIdRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdRouteWithChildren
  AuthenticatedOrgsOrgIdAgentsIndexRoute: typeof AuthenticatedOrgsOrgIdAgentsIndexRoute
}

const AuthenticatedOrgsOrgIdAgentsRouteChildren: AuthenticatedOrgsOrgIdAgentsRouteChildren =
  {
    AuthenticatedOrgsOrgIdAgentsAgentIdRoute:
      AuthenticatedOrgsOrgIdAgentsAgentIdRouteWithChildren,
    AuthenticatedOrgsOrgIdAgentsIndexRoute:
      AuthenticatedOrgsOrgIdAgentsIndexRoute,
  }

const AuthenticatedOrgsOrgIdAgentsRouteWithChildren =
  AuthenticatedOrgsOrgIdAgentsRoute._addFileChildren(
    AuthenticatedOrgsOrgIdAgentsRouteChildren,
  )

interface AuthenticatedOrgsOrgIdRouteChildren {
  AuthenticatedOrgsOrgIdAgentsRoute: typeof AuthenticatedOrgsOrgIdAgentsRouteWithChildren
  AuthenticatedOrgsOrgIdMembersRoute: typeof AuthenticatedOrgsOrgIdMembersRoute
  AuthenticatedOrgsOrgIdSettingsRoute: typeof AuthenticatedOrgsOrgIdSettingsRoute
  AuthenticatedOrgsOrgIdIndexRoute: typeof AuthenticatedOrgsOrgIdIndexRoute
}

const AuthenticatedOrgsOrgIdRouteChildren: AuthenticatedOrgsOrgIdRouteChildren =
  {
    AuthenticatedOrgsOrgIdAgentsRoute:
      AuthenticatedOrgsOrgIdAgentsRouteWithChildren,
    AuthenticatedOrgsOrgIdMembersRoute: AuthenticatedOrgsOrgIdMembersRoute,
    AuthenticatedOrgsOrgIdSettingsRoute: AuthenticatedOrgsOrgIdSettingsRoute,
    AuthenticatedOrgsOrgIdIndexRoute: AuthenticatedOrgsOrgIdIndexRoute,
  }

const AuthenticatedOrgsOrgIdRouteWithChildren =
  AuthenticatedOrgsOrgIdRoute._addFileChildren(
    AuthenticatedOrgsOrgIdRouteChildren,
  )

interface AuthenticatedOrgsRouteChildren {
  AuthenticatedOrgsOrgIdRoute: typeof AuthenticatedOrgsOrgIdRouteWithChildren
  AuthenticatedOrgsIndexRoute: typeof AuthenticatedOrgsIndexRoute
}

const AuthenticatedOrgsRouteChildren: AuthenticatedOrgsRouteChildren = {
  AuthenticatedOrgsOrgIdRoute: AuthenticatedOrgsOrgIdRouteWithChildren,
  AuthenticatedOrgsIndexRoute: AuthenticatedOrgsIndexRoute,
}

const AuthenticatedOrgsRouteWithChildren =
  AuthenticatedOrgsRoute._addFileChildren(AuthenticatedOrgsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrgsRoute: typeof AuthenticatedOrgsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrgsRoute: AuthenticatedOrgsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicExotelAudioAudioIdRoute: ApiPublicExotelAudioAudioIdRoute,
  ApiPublicExotelVoiceAudioIdRoute: ApiPublicExotelVoiceAudioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
