/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOrgsIndexRouteImport } from './routes/_authenticated/orgs.index'
import { Route as AuthenticatedOrgsOrgIdAgentsIndexRouteImport } from './routes/_authenticated/orgs.$orgId.agents.index'
import { Route as AuthenticatedOrgsOrgIdAgentsAgentIdIndexRouteImport } from './routes/_authenticated/orgs.$orgId.agents.$agentId.index'
import { Route as AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRouteImport } from './routes/_authenticated/orgs.$orgId.agents.$agentId.flows.$flowId.index'
import { Route as AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRouteImport } from './routes/_authenticated/orgs.$orgId.agents.$agentId.flows.$flowId.versions'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgsIndexRoute = AuthenticatedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgsOrgIdAgentsIndexRoute =
  AuthenticatedOrgsOrgIdAgentsIndexRouteImport.update({
    id: '/orgs/$orgId/agents/',
    path: '/orgs/$orgId/agents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute =
  AuthenticatedOrgsOrgIdAgentsAgentIdIndexRouteImport.update({
    id: '/orgs/$orgId/agents/$agentId/',
    path: '/orgs/$orgId/agents/$agentId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute =
  AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRouteImport.update({
    id: '/orgs/$orgId/agents/$agentId/flows/$flowId/',
    path: '/orgs/$orgId/agents/$agentId/flows/$flowId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute =
  AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRouteImport.update({
    id: '/orgs/$orgId/agents/$agentId/flows/$flowId/versions',
    path: '/orgs/$orgId/agents/$agentId/flows/$flowId/versions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/orgs/$orgId/agents/': typeof AuthenticatedOrgsOrgIdAgentsIndexRoute
  '/orgs/$orgId/agents/$agentId/': typeof AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute
  '/orgs/$orgId/agents/$agentId/flows/$flowId/versions': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute
  '/orgs/$orgId/agents/$agentId/flows/$flowId/': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/orgs': typeof AuthenticatedOrgsIndexRoute
  '/orgs/$orgId/agents': typeof AuthenticatedOrgsOrgIdAgentsIndexRoute
  '/orgs/$orgId/agents/$agentId': typeof AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute
  '/orgs/$orgId/agents/$agentId/flows/$flowId/versions': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute
  '/orgs/$orgId/agents/$agentId/flows/$flowId': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/orgs/': typeof AuthenticatedOrgsIndexRoute
  '/_authenticated/orgs/$orgId/agents/': typeof AuthenticatedOrgsOrgIdAgentsIndexRoute
  '/_authenticated/orgs/$orgId/agents/$agentId/': typeof AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute
  '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/versions': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute
  '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/': typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/orgs/'
    | '/orgs/$orgId/agents/'
    | '/orgs/$orgId/agents/$agentId/'
    | '/orgs/$orgId/agents/$agentId/flows/$flowId/versions'
    | '/orgs/$orgId/agents/$agentId/flows/$flowId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/orgs'
    | '/orgs/$orgId/agents'
    | '/orgs/$orgId/agents/$agentId'
    | '/orgs/$orgId/agents/$agentId/flows/$flowId/versions'
    | '/orgs/$orgId/agents/$agentId/flows/$flowId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/orgs/'
    | '/_authenticated/orgs/$orgId/agents/'
    | '/_authenticated/orgs/$orgId/agents/$agentId/'
    | '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/versions'
    | '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orgs/': {
      id: '/_authenticated/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AuthenticatedOrgsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/$orgId/agents/': {
      id: '/_authenticated/orgs/$orgId/agents/'
      path: '/orgs/$orgId/agents'
      fullPath: '/orgs/$orgId/agents/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/$orgId/agents/$agentId/': {
      id: '/_authenticated/orgs/$orgId/agents/$agentId/'
      path: '/orgs/$orgId/agents/$agentId'
      fullPath: '/orgs/$orgId/agents/$agentId/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/': {
      id: '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/'
      path: '/orgs/$orgId/agents/$agentId/flows/$flowId'
      fullPath: '/orgs/$orgId/agents/$agentId/flows/$flowId/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/versions': {
      id: '/_authenticated/orgs/$orgId/agents/$agentId/flows/$flowId/versions'
      path: '/orgs/$orgId/agents/$agentId/flows/$flowId/versions'
      fullPath: '/orgs/$orgId/agents/$agentId/flows/$flowId/versions'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrgsIndexRoute: typeof AuthenticatedOrgsIndexRoute
  AuthenticatedOrgsOrgIdAgentsIndexRoute: typeof AuthenticatedOrgsOrgIdAgentsIndexRoute
  AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute
  AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute
  AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute: typeof AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrgsIndexRoute: AuthenticatedOrgsIndexRoute,
  AuthenticatedOrgsOrgIdAgentsIndexRoute:
    AuthenticatedOrgsOrgIdAgentsIndexRoute,
  AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute:
    AuthenticatedOrgsOrgIdAgentsAgentIdIndexRoute,
  AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute:
    AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdVersionsRoute,
  AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute:
    AuthenticatedOrgsOrgIdAgentsAgentIdFlowsFlowIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
